#ifndef BUILTIN_H
#define BUILTIN_H

enum BuiltinOp {
    // arith
    OP_ADD_8,
    OP_ADD_16,
    OP_SUB_8,
    OP_SUB_16,
    OP_AND_8,
    OP_AND_16,
    OP_OR_8,
    OP_OR_16,
    OP_XOR_8,
    OP_XOR_16,
    OP_NOT_8,
    OP_NOT_16,
    OP_LOGICAL_AND,
    OP_LOGICAL_OR,
    OP_LOGICAL_NOT,
    OP_MUL_8,
    OP_MUL_16,
    OP_DIV_U8,
    OP_DIV_I8,
    OP_DIV_U16,
    OP_DIV_I16,
    OP_MOD_U8,
    OP_MOD_I8,
    OP_MOD_U16,
    OP_MOD_I16,
    OP_LSL_8,
    OP_LSL_16,
    OP_LSR_8,
    OP_LSR_16,
    OP_ASR_8,
    OP_ASR_16,
    OP_UNARY_NEG_8,
    OP_UNARY_NEG_16,
    // assign ops
    OP_ASSIGN_8,
    OP_ASSIGN_16,
    OP_ASSIGN_SIZED, /* structs, arrays, etc */
    OP_ADD_ASSIGN_8,
    OP_ADD_ASSIGN_16,
    OP_SUB_ASSIGN_8,
    OP_SUB_ASSIGN_16,
    OP_MUL_ASSIGN_8,
    OP_MUL_ASSIGN_16,
    OP_DIV_ASSIGN_U8,
    OP_DIV_ASSIGN_I8,
    OP_DIV_ASSIGN_U16,
    OP_DIV_ASSIGN_I16,
    OP_MOD_ASSIGN_U8,
    OP_MOD_ASSIGN_I8,
    OP_MOD_ASSIGN_U16,
    OP_MOD_ASSIGN_I16,
    OP_LSL_ASSIGN_8,
    OP_LSL_ASSIGN_16,
    OP_LSR_ASSIGN_8,
    OP_LSR_ASSIGN_16,
    OP_ASR_ASSIGN_8,
    OP_ASR_ASSIGN_16,
    OP_AND_ASSIGN_8,
    OP_AND_ASSIGN_16,
    OP_OR_ASSIGN_8,
    OP_OR_ASSIGN_16,
    OP_XOR_ASSIGN_8,
    OP_XOR_ASSIGN_16,
    // comparisons
    OP_EQ_SIZED, /* structs, arrays, etc */
    OP_NEQ_SIZED, /* structs, arrays, etc */
    OP_EQ_8,
    OP_EQ_16,
    OP_NEQ_8,
    OP_NEQ_16,
    OP_LT_U8,
    OP_LT_U16,
    OP_GT_U8,
    OP_GT_U16,
    OP_LTE_U8,
    OP_LTE_U16,
    OP_GTE_U8,
    OP_GTE_U16,
    OP_LT_I8,
    OP_LT_I16,
    OP_GT_I8,
    OP_GT_I16,
    OP_LTE_I8,
    OP_LTE_I16,
    OP_GTE_I8,
    OP_GTE_I16,
    // pointer stuff
    OP_ARRAY_INDEX_8,
    OP_ARRAY_INDEX_16,
    OP_ADDRESSOF,
    OP_DEREF,
    OP_PTR_ADD,
    OP_PTR_SUB,
    OP_PTR_ADD_ASSIGN,
    OP_PTR_SUB_ASSIGN,
};

#endif /* BUILTIN_H */
